import jsPDF from 'jspdf'

const generateInterviewPDF = (interviewData) => {
  const doc = new jsPDF()
  
  const { userName, interviewType, date, overallScore, questions } = interviewData

  // Header
  doc.setFillColor(88, 28, 135)
  doc.rect(0, 0, 210, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('AI Interview Coach', 105, 18, { align: 'center' })
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text('Interview Performance Report', 105, 30, { align: 'center' })

  // Reset color
  doc.setTextColor(0, 0, 0)

  // Info section
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Candidate Information', 20, 55)
  doc.setLineWidth(0.5)
  doc.line(20, 58, 190, 58)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(`Name: ${userName}`, 20, 68)
  doc.text(`Interview Type: ${interviewType}`, 20, 78)
  doc.text(`Date: ${date}`, 20, 88)
  doc.text(`Overall Score: ${overallScore}/10`, 20, 98)

  // Score box
  doc.setFillColor(245, 240, 255)
  doc.rect(130, 62, 60, 30, 'F')
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(88, 28, 135)
  doc.text(`${overallScore}/10`, 160, 82, { align: 'center' })
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('Overall Score', 160, 88, { align: 'center' })

  // Questions section
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Interview Questions & Feedback', 20, 115)
  doc.line(20, 118, 190, 118)

  let yPos = 128

  questions.forEach((q, index) => {
    // Check if new page needed
    if (yPos > 250) {
      doc.addPage()
      yPos = 20
    }

    // Question number
    doc.setFillColor(88, 28, 135)
    doc.circle(25, yPos - 3, 4, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.text(`${index + 1}`, 25, yPos - 1, { align: 'center' })

    // Question
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    const questionLines = doc.splitTextToSize(`Q: ${q.question}`, 155)
    doc.text(questionLines, 33, yPos)
    yPos += questionLines.length * 6 + 4

    // Score badge
    doc.setFillColor(220, 252, 231)
    doc.rect(33, yPos - 4, 30, 8, 'F')
    doc.setTextColor(22, 101, 52)
    doc.setFontSize(10)
    doc.text(`Score: ${q.score}/10`, 48, yPos + 1, { align: 'center' })
    yPos += 10

    // User answer
    doc.setTextColor(60, 60, 60)
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(10)
    const answerLines = doc.splitTextToSize(`Your Answer: ${q.userAnswer}`, 165)
    doc.text(answerLines, 33, yPos)
    yPos += answerLines.length * 5 + 4

    // AI Feedback
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    const feedbackLines = doc.splitTextToSize(`AI Feedback: ${q.aiFeedback}`, 165)
    doc.text(feedbackLines, 33, yPos)
    yPos += feedbackLines.length * 5 + 10

    // Divider
    doc.setDrawColor(200, 200, 200)
    doc.line(20, yPos, 190, yPos)
    yPos += 8
  })

  // Footer
  doc.setFillColor(88, 28, 135)
  doc.rect(0, 285, 210, 12, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.text('Generated by AI Interview Coach', 105, 293, { align: 'center' })

  // Save
  doc.save(`Interview_Report_${interviewType}_${date}.pdf`)
}

export default generateInterviewPDF